spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zhaobohan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML5

server:
  port: 8080

#    prefix: classpath:/templates/
#    suffix: .html
#    servlet:
#      content-type: test/html
#    encoding: utf-8
#    cache: false
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/static

#logging:
#  level:
#    root: info
#    com.zbh: debug
#  file:
#    name: log/blog.log

